# -*- coding: utf-8 -*-
"""simulmc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfekAMImX64eg3Q7Zc0A-pO4X9vREKw4
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# CONFIGURACIÓN
# ============================================================

st.set_page_config(
    page_title="GBM - Simulación Monte Carlo",
    page_icon="📈",
    layout="wide"
)

st.title("📈 Simulación Monte Carlo con Movimiento Geométrico Browniano")

st.markdown("""
### Simulación de inversiones

La aplicación utiliza precios históricos de Yahoo Finance para estimar
los parámetros del **Movimiento Geométrico Browniano (GBM)** y generar
escenarios futuros mediante simulación Monte Carlo.

**Inversión inicial: $100,000 MXN**
""")

# ============================================================
# UNIVERSO DE ACTIVOS
# ============================================================

TICKERS = [
"GAPB.MX","SPY", "GRUMAB.MX",  "NVDA","QUBT", "QTUM", "VOO", "QQQ", 
"AVGO", "ASURB.MX", "QBTS" , "^GSPC","BTC-USD", "BABA", "VISTAA.MX", "DANHOS13.MX", "EDUCA18.MX",
"FIBRAMQ12.MX", "FIBRAPL14.MX", "FIHO12.MX", "FINN13.MX", "FMTY14.MX",
"FPLUS16.MX", "FSHOP13.MX", "FUNO11.MX", "ACCELSAB.MX", "AGUA.MX", 
"CADUA.MX", "CERAMICB.MX", "DINEB.MX",  "GCARSOA1.MX",
"GISSAA.MX", "GMD.MX",  "HOMEX.MX",  "KUOB.MX",
"OMAB.MX", "ORBIA.MX", "PASAB.MX", "PINFRA.MX", "SITES1A-1.MX", "TMMA.MX",
"TRAXIONA.MX", "VESTA.MX", "VINTE.MX", "VOLARA.MX", "ALPEKA.MX", "AUTLANB.MX",
"CEMEXCPO.MX", "CMOCTEZ.MX", "COLLADO.MX", "CONVERA.MX", "CYDSASAA.MX",
"GCC.MX", "GMEXICOB.MX", "ICHB.MX", "LAMOSA.MX", "MFRISCOA-1.MX",
"PE&OLES.MX", "POCHTECB.MX", "SIMECB.MX", "TEAKCPO.MX", "VITROA.MX",
"AC.MX", "BIMBOA.MX", "CHDRAUIB.MX", "CUERVO.MX", "CULTIBAB.MX",
"FEMSAUBD.MX", "GIGANTE.MX", "GRUMAB.MX", "HERDEZ.MX", "KIMBERA.MX",
"KOFUBL.MX", "LACOMERUBC.MX", "MINSAB.MX", "SORIANAB.MX", "WALMEX.MX",
"BEVIDESB.MX", "FRAGUAB.MX", "LABB.MX", "MEDICAB.MX", "AMXB.MX",
"AXTELCPO.MX", "CABLECPO.MX", "CTAXTELA.MX", "MEGACPO.MX", "TLEVISACPO.MX",
"ACTINVRB.MX", "BBAJIOO.MX", "BOLSAA.MX", "CREAL.MX", "FINAMEXO.MX",
"FINDEP.MX", "GBMO.MX", "GENTERA.MX", "GFINBURO.MX", "GFNORTEO.MX",
"GNP.MX", "GPROFUT.MX", "INVEXA.MX", "PROCORPB.MX", "Q.MX", "RA.MX",
"AGUILASCPO.MX", "ALSEA.MX", "CIDMEGA.MX", "CIEB.MX", "CMRB.MX",
"HCITY.MX", "HOTEL.MX", "LIVEPOL1.MX", "NEMAKA.MX", "POSADASA.MX",
"RLHA.MX", "SPORTS.MX", "VASCONI.MX", "ARKB", "BTCW", "BTCO", "BITB",
"HODL", "EZBC", "FBTC", "BRRR", "GBTC", "DEFI", "IBIT", "ACWI",
"FAS", "SPXL", "TECL", "IAU", "NU", "MELI", "META",
"JPM","NFLX", "IONQ", "RGTI", "PLTR", "SOFI", "HOOD", "FRES.MX", "MCHI", "INDA", "TSM", "AMD", "GOOGL", "AMZN","V"

]

# ============================================================
# PARÁMETROS
# ============================================================

col1, col2 = st.columns(2)

with col1:

    periodo = st.selectbox(
        "⏱️ Periodo histórico",
        [
            "6 meses",
            "1 año",
            "2 años",
            "3 años",
            "5 años",
            "10 años"
        ],
        index=2
    )

with col2:

    simulaciones = st.number_input(
        "🎲 Número de simulaciones",
        min_value=100,
        max_value=100000,
        value=10000,
        step=1000
    )

# Conversión a formato yfinance
periodos_yf = {
    "6 meses": "6mo",
    "1 año": "1y",
    "2 años": "2y",
    "3 años": "3y",
    "5 años": "5y",
    "10 años": "10y"
}

periodo_yf = periodos_yf[periodo]

# ============================================================
# INVERSIÓN
# ============================================================

INVERSION = 100000

st.info(
    f"💰 Inversión inicial utilizada: **${INVERSION:,.0f} MXN**"
)

# ============================================================
# EXPLICACIÓN DEL MODELO
# ============================================================

with st.expander("📐 Modelo matemático utilizado"):

    st.latex(
        r"""
        dS_t=\mu S_tdt+\sigma S_tdW_t
        """
    )

    st.markdown(
        "La solución exacta del Movimiento Geométrico Browniano es:"
    )

    st.latex(
        r"""
        S_{t+\Delta t}
        =
        S_t
        \exp
        \left[
        \left(
        \mu-\frac{1}{2}\sigma^2
        \right)\Delta t
        +
        \sigma\sqrt{\Delta t}Z_t
        \right]
        """
    )

    st.markdown(
        "donde:"
    )

    st.latex(
        r"""
        Z_t\sim N(0,1)
        """
    )

# ============================================================
# BOTÓN
# ============================================================

ejecutar = st.button(
    "🚀 Ejecutar simulación GBM",
    type="primary",
    use_container_width=True
)

# ============================================================
# FUNCIÓN PARA DESCARGAR PRECIOS
# ============================================================

def obtener_precios(ticker, periodo):

    try:

        df = yf.download(
            ticker,
            period=periodo,
            interval="1d",
            auto_adjust=True,
            progress=False,
            threads=False,
            multi_level_index=False
        )

        if df is None or df.empty:
            return None

        if "Close" not in df.columns:
            return None

        precios = df["Close"].dropna()

        if len(precios) < 30:
            return None

        return precios

    except Exception:

        return None


# ============================================================
# SIMULACIÓN
# ============================================================

if ejecutar:

    resultados = []

    simulaciones_activos = {}

    progreso = st.progress(0)

    mensaje = st.empty()

    total = len(TICKERS)

    # ========================================================
    # PROCESAR CADA ACTIVO
    # ========================================================

    for i, ticker in enumerate(TICKERS):

        mensaje.write(
            f"Procesando **{ticker}**..."
        )

        try:

            # ------------------------------------------------
            # PRECIOS HISTÓRICOS
            # ------------------------------------------------

            precios = obtener_precios(
                ticker,
                periodo_yf
            )

            if precios is None:
                progreso.progress(
                    (i + 1) / total
                )
                continue

            # ------------------------------------------------
            # RENDIMIENTOS LOGARÍTMICOS
            # ------------------------------------------------

            log_returns = np.log(
                precios / precios.shift(1)
            ).dropna()

            if len(log_returns) < 20:
                progreso.progress(
                    (i + 1) / total
                )
                continue

            # ------------------------------------------------
            # PARÁMETROS DIARIOS
            # ------------------------------------------------

            mu_diaria = log_returns.mean()

            sigma_diaria = log_returns.std()

            # ------------------------------------------------
            # PARÁMETROS ANUALIZADOS
            # ------------------------------------------------

            mu_anual = mu_diaria * 252

            sigma_anual = sigma_diaria * np.sqrt(252)

            # ------------------------------------------------
            # PRECIO ACTUAL
            # ------------------------------------------------

            S0 = float(
                precios.iloc[-1]
            )

            # ------------------------------------------------
            # HORIZONTE FUTURO
            #
            # Se simula un número de días equivalente
            # a las observaciones históricas.
            # ------------------------------------------------

            dias_futuros = len(log_returns)

            dt = 1 / 252

            # ------------------------------------------------
            # GENERACIÓN DE VARIABLES ALEATORIAS
            # ------------------------------------------------

            rng = np.random.default_rng(
                1000 + i
            )

            Z = rng.normal(
                0,
                1,
                size=(
                    int(simulaciones),
                    dias_futuros
                )
            )

            # ------------------------------------------------
            # MOVIMIENTO GEOMÉTRICO BROWNIANO
            # ------------------------------------------------

            incremento = (
                (
                    mu_anual
                    -
                    0.5 * sigma_anual ** 2
                )
                * dt
                +
                sigma_anual
                * np.sqrt(dt)
                * Z
            )

            # ------------------------------------------------
            # TRAYECTORIAS
            # ------------------------------------------------

            trayectorias = (
                S0
                *
                np.exp(
                    np.cumsum(
                        incremento,
                        axis=1
                    )
                )
            )

            # ------------------------------------------------
            # PRECIO FINAL
            # ------------------------------------------------

            precio_final = (
                trayectorias[:, -1]
            )

            # ------------------------------------------------
            # RENDIMIENTO
            # ------------------------------------------------

            rendimiento = (
                precio_final / S0
            ) - 1

            # ------------------------------------------------
            # VALOR FINAL DE LA INVERSIÓN
            # ------------------------------------------------

            valor_final = (
                INVERSION
                *
                (1 + rendimiento)
            )

            # ------------------------------------------------
            # GANANCIA / PÉRDIDA
            # ------------------------------------------------

            ganancia = (
                valor_final
                -
                INVERSION
            )

            # ------------------------------------------------
            # ESTADÍSTICAS
            # ------------------------------------------------

            rendimiento_promedio = np.mean(
                rendimiento
            )

            mediana = np.median(
                rendimiento
            )

            p5 = np.percentile(
                rendimiento,
                5
            )

            p95 = np.percentile(
                rendimiento,
                95
            )

            valor_promedio = np.mean(
                valor_final
            )

            ganancia_promedio = np.mean(
                ganancia
            )

            # ------------------------------------------------
            # VaR 95%
            # ------------------------------------------------

            VaR_95 = max(
                0,
                -INVERSION * p5
            )

            # ------------------------------------------------
            # CVaR 95%
            # ------------------------------------------------

            cola = rendimiento[
                rendimiento <= p5
            ]

            if len(cola) > 0:

                cvar_rendimiento = np.mean(
                    cola
                )

            else:

                cvar_rendimiento = p5

            CVaR_95 = max(
                0,
                -INVERSION * cvar_rendimiento
            )

            # ------------------------------------------------
            # PROBABILIDAD DE GANANCIA
            # ------------------------------------------------

            prob_ganancia = np.mean(
                rendimiento > 0
            )

            # ------------------------------------------------
            # GUARDAR RESULTADOS
            # ------------------------------------------------

            resultados.append({

                "Ticker":
                    ticker,

                "Rendimiento promedio":
                    rendimiento_promedio,

                "Mediana":
                    mediana,

                "Valor final promedio":
                    valor_promedio,

                "Ganancia promedio":
                    ganancia_promedio,

                "VaR 95%":
                    VaR_95,

                "CVaR 95%":
                    CVaR_95,

                "P5":
                    p5,

                "P95":
                    p95,

                "Probabilidad de ganancia":
                    prob_ganancia,

                "μ anual":
                    mu_anual,

                "σ anual":
                    sigma_anual,

                "Precio actual":
                    S0
            })

            # ------------------------------------------------
            # GUARDAR SIMULACIONES
            # ------------------------------------------------

            simulaciones_activos[ticker] = {

                "trayectorias":
                    trayectorias,

                "rendimiento":
                    rendimiento,

                "valor_final":
                    valor_final
            }

        except Exception:

            pass

        progreso.progress(
            (i + 1) / total
        )

    mensaje.empty()

    # ========================================================
    # COMPROBAR RESULTADOS
    # ========================================================

    if len(resultados) == 0:

        st.error(
            "No fue posible obtener información suficiente "
            "de los activos."
        )

    else:

        # ====================================================
        # DATAFRAME
        # ====================================================

        df_resultados = pd.DataFrame(
            resultados
        )

        # ====================================================
        # RANKING
        # ====================================================

        df_resultados = df_resultados.sort_values(
            "Rendimiento promedio",
            ascending=False
        ).reset_index(drop=True)

        df_resultados.insert(
            0,
            "Ranking",
            range(
                1,
                len(df_resultados) + 1
            )
        )

        # ====================================================
        # RESUMEN
        # ====================================================

        st.success(
            f"Simulación terminada. "
            f"Se procesaron {len(df_resultados)} activos."
        )

        # ====================================================
        # PRIMER ACTIVO DEL RANKING
        # ====================================================

        primero = df_resultados.iloc[0]

        c1, c2, c3, c4 = st.columns(4)

        with c1:

            st.metric(
                "Activo",
                primero["Ticker"]
            )

        with c2:

            st.metric(
                "Rendimiento promedio",
                f"{primero['Rendimiento promedio']:.2%}"
            )

        with c3:

            st.metric(
                "Valor final promedio",
                f"${primero['Valor final promedio']:,.0f}"
            )

        with c4:

            st.metric(
                "Probabilidad de ganancia",
                f"{primero['Probabilidad de ganancia']:.2%}"
            )

        # ====================================================
        # TABLA PRINCIPAL
        # ====================================================

        st.markdown(
            "## 🏆 Ranking de activos"
        )

        st.dataframe(

            df_resultados.style.format({

                "Rendimiento promedio":
                    "{:.2%}",

                "Mediana":
                    "{:.2%}",

                "Valor final promedio":
                    "${:,.0f}",

                "Ganancia promedio":
                    "${:,.0f}",

                "VaR 95%":
                    "${:,.0f}",

                "CVaR 95%":
                    "${:,.0f}",

                "P5":
                    "{:.2%}",

                "P95":
                    "{:.2%}",

                "Probabilidad de ganancia":
                    "{:.2%}",

                "μ anual":
                    "{:.2%}",

                "σ anual":
                    "{:.2%}",

                "Precio actual":
                    "${:,.2f}"
            }),

            use_container_width=True,

            height=650
        )

        # ====================================================
        # GRÁFICA 1
        # RENDIMIENTO
        # ====================================================

        st.markdown(
            "## 📊 Ranking de rendimiento promedio"
        )

        fig, ax = plt.subplots(
            figsize=(15, 7)
        )

        ax.bar(
            df_resultados["Ticker"],
            df_resultados[
                "Rendimiento promedio"
            ] * 100
        )

        ax.axhline(
            0,
            linewidth=1
        )

        ax.set_ylabel(
            "Rendimiento promedio (%)"
        )

        ax.set_xlabel(
            "Activo"
        )

        ax.set_title(
            "Rendimiento simulado mediante GBM"
        )

        plt.xticks(
            rotation=90
        )

        plt.tight_layout()

        st.pyplot(fig)

        # ====================================================
        # GRÁFICA 2
        # VALOR FINAL
        # ====================================================

        st.markdown(
            "## 💰 Valor final promedio"
        )

        df_valor = df_resultados.sort_values(
            "Valor final promedio",
            ascending=False
        )

        fig, ax = plt.subplots(
            figsize=(15, 7)
        )

        ax.bar(
            df_valor["Ticker"],
            df_valor[
                "Valor final promedio"
            ]
        )

        ax.axhline(
            INVERSION,
            linewidth=2,
            linestyle="--"
        )

        ax.set_ylabel(
            "Valor final ($)"
        )

        ax.set_xlabel(
            "Activo"
        )

        ax.set_title(
            "Valor final promedio de $100,000"
        )

        plt.xticks(
            rotation=90
        )

        plt.tight_layout()

        st.pyplot(fig)

        # ====================================================
        # GRÁFICA 3
        # VaR Y CVaR
        # ====================================================

        st.markdown(
            "## ⚠️ VaR y CVaR al 95%"
        )

        fig, ax = plt.subplots(
            figsize=(15, 7)
        )

        x = np.arange(
            len(df_resultados)
        )

        ax.bar(
            x - 0.2,
            df_resultados["VaR 95%"],
            width=0.4,
            label="VaR 95%"
        )

        ax.bar(
            x + 0.2,
            df_resultados["CVaR 95%"],
            width=0.4,
            label="CVaR 95%"
        )

        ax.set_xticks(x)

        ax.set_xticklabels(
            df_resultados["Ticker"],
            rotation=90
        )

        ax.set_ylabel(
            "Pérdida ($)"
        )

        ax.set_title(
            "Riesgo de pérdida para $100,000"
        )

        ax.legend()

        plt.tight_layout()

        st.pyplot(fig)

        # ====================================================
        # TOP 5
        # TRAYECTORIAS GBM
        # ====================================================

        st.markdown(
            "## 🎲 Trayectorias simuladas"
        )

        st.caption(
            "Se muestran hasta 100 trayectorias de los cinco "
            "activos con mayor rendimiento promedio simulado."
        )

        top5 = df_resultados.head(5)[
            "Ticker"
        ].tolist()

        for ticker in top5:

            trayectorias = (
                simulaciones_activos[
                    ticker
                ]["trayectorias"]
            )

            numero_mostrar = min(
                100,
                len(trayectorias)
            )

            fig, ax = plt.subplots(
                figsize=(12, 5)
            )

            ax.plot(
                trayectorias[
                    :numero_mostrar
                ].T,
                alpha=0.08
            )

            ax.axhline(
                np.mean(
                    trayectorias[:, -1]
                ),
                linewidth=2,
                linestyle="--",
                label="Precio final promedio"
            )

            ax.axhline(
                trayectorias[0, 0],
                linewidth=1,
                linestyle=":",
                label="Precio inicial"
            )

            ax.set_title(
                f"{ticker} — Trayectorias GBM"
            )

            ax.set_xlabel(
                "Días"
            )

            ax.set_ylabel(
                "Precio"
            )

            ax.legend()

            plt.tight_layout()

            st.pyplot(fig)

        # ====================================================
        # DESCARGA CSV
        # ====================================================

        csv = df_resultados.to_csv(
            index=False,
            encoding="utf-8-sig"
        )

        st.download_button(
            "⬇️ Descargar resultados CSV",
            data=csv,
            file_name="simulacion_GBM.csv",
            mime="text/csv",
            use_container_width=True
        )
